name: libclang-windows-amd64

on: [push, pull_request]

env:
  LLVM_VER: 11.0.0

jobs:
  build-and-deploy:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: get llvm-project
      run: |
        choco install wget
        wget https://github.com/llvm/llvm-project/releases/download/llvmorg-%LLVM_VER%/llvm-project-%LLVM_VER%.tar.xz
        $env:Path = "C:\Program Files\Git\usr\bin;$env:Path"
        tar xf llvm-project-%LLVM_VER%.tar.xz --exclude=llvm-project-%LLVM_VER%/clang/test/Driver/Inputs* --exclude=llvm-project-%LLVM_VER%/libclc/amdgcn-mesa3d --exclude=llvm-project-%LLVM_VER%/libcxx/test/std/input.output/filesystems/Inputs/static_test_env/*
    - name: make build directory
      run: mkdir -p llvm-project-%LLVM_VER%/build
    - name: cmake
      run: cd llvm-project-%LLVM_VER%/build && cmake ../llvm -Thost=x64 -DLLVM_ENABLE_PROJECTS=clang -DBUILD_SHARED_LIBS=OFF -DLLVM_TARGETS_TO_BUILD=X86 -DCMAKE_CXX_FLAGS="/MP" -DLLVM_USE_CRT_MINSIZEREL="MT"
    - name: build
      run: cd llvm-project-%LLVM_VER%/build && cmake --build . --config MinSizeRel --target libclang
    - name: create and print sha512sum
      run: |
        $env:Path = "C:\Program Files\Git\usr\bin;$env:Path"
        cd llvm-project-%LLVM_VER%\build\MinSizeRel\bin
        sha512sum.exe libclang.dll > libclang.dll.%LLVM_VER%.windows-amd64.sha512sum
        echo "Checksum is: "
        Get-Content -Path libclang.dll.%LLVM_VER%.windows-amd64.sha512sum
        tar zcvf libclang.dll.%LLVM_VER%.windows-amd64.tar.gz libclang.dll libclang.dll.%LLVM_VER%.windows-amd64.sha512sum
    - uses: actions/upload-artifact@v2
      with:
        name: libclang.dll.%LLVM_VER%.windows-amd64.tar.gz
        path: llvm-project-%LLVM_VER%\build\MinSizeRel\bin\libclang.dll.%LLVM_VER%.windows-amd64.tar.gz
